### ISSUE TITLE
Don't split hyphenated words

### ISSUE THREAD

**Issue by cacoethes** [jamestomasino/stutter#10]
Words like "on-call" are split into "on-", and "call" with a punctuation pause between the two.

**Comment by jamestomasino** [comment]
I can introduce a check to see if the compound word is within the 13 character single-block maximum and then attempt to leave it unbroken. The dashes are often a very convenient point to introduce blocking, though.

**Comment by jamestomasino** [comment]
Hrm, I have a draft that doesn't quite work. I can detect if we're < 13 and leave -'s alone, but then it's overzealous and leaves double-dashes too, which really should split. I'm trying combinations of negative lookaheads to get around it but it's eluding me still. More work to come.

**Comment by jamestomasino** [comment]
#38 relates

**Comment by jamestomasino** [comment]
The maximum word length is now an option. Lets see if we can make progress on the hyphen splitting now.

**Comment by jamestomasino** [comment]
This is fixed in v1.8.1.

I split hyphenated words only if the word exceeds the Maximum Word Length setting. When a long word is found it first splits on any hyphens found. If any of the remaining parts, or the word itself, is still too long it will use the word parts to break up the word by common prefixes and suffixes. Finally, if all else fails, we use common vowel/consonant patterns to try and break it somewhere that's not too bad.

**Comment by thiswillbeyourgithub** [comment]
In the same vein : I think that `i. e.` or variant of this should not be splitted
