### ISSUE TITLE
[request] Length for word split

### ISSUE THREAD

**Issue by PhunkyBob** [jamestomasino/stutter#38]
Hello,

I notice that a lot of words are splitted and separated by "-".
I think it's easier to read a "not so long word" than "2 splitted parts of a not so long word". 
For instance, the word "enregistrement" is splitted in 3 parts: "en-", "-registre-", "-ment"

Would it be possible to choose from which length a word would be cut out?

Thank you.

**Comment by jamestomasino** [comment]
Hi @PhunkyBob I was using some of the RSVP research showing words of certain lengths show better comprehension when broken up and set the threshhold for the "break-up" at 13 characters. The logic for that happens in `block.js`. I suppose I could move that to a configuration setting, though.

The logic that happens when we break up long words is fairly sophisticated. I'm using common prefixes and suffixes and vowel patterns of english to determine where to best break the word. This is also the biggest area that's a challenge for internationalization.

Anyway, I think the 13 character line is something I should be able to tweak into the settings screen for you.

**Comment by jamestomasino** [comment]
#10 relates

**Comment by jamestomasino** [comment]
This is resolved in v1.8.0

There is now an option in the settings page allowing the maximum word length between 5 and 50 characters.

**Comment by PhunkyBob** [comment]
Thank you!

**Comment by jamestomasino** [comment]
@PhunkyBob FF version is already published. Chrome is "in review". Hopefully the update will be live in the next few hours there too.

**Comment by PhunkyBob** [comment]
I've updated and it seems to work for me.
