### ISSUE TITLE
regression ? hotkeys not working anymore

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#46]
Hello again !

I updated the addon today and hotkeys seem to have stopped working. I can't speed up/down escape pause or skip. I don't think I have changed anything since yesterday, and I tried restarting firefox to no avail.

Any idea ?

**Comment by jamestomasino** [comment]
Curses! You're right.

**Comment by jamestomasino** [comment]
Fixed in v1.9.2.

**Comment by thiswillbeyourgithub** [comment]
So, now stutter keybindings work but the spacebar doesn't anymore. It used to allow for 1 page scrolling while reading, which I was using.

Does it have to be this way ? I think it's nice to scroll via space bar to see pictures at the same time as RSVP.

**Comment by jamestomasino** [comment]
Well that's different. I'm not binding the spacebar at all. It's a built-in browser behavior that I like and use, which is why I went with the "enter" key as the play/pause toggle instead. Really that's not great either. I'm thinking I should use the alt+shift+<action-key> combo for everything to try and avoid bindings that are already in use. The alt+left & alt+right are already history nav, after all. I'm now using alt+shift+r

**Comment by thiswillbeyourgithub** [comment]
Personnaly I set the shortcut to launch RSVP to ctrl+alt+spacebar, not very elegant but it does the job with a single left hand. The default alt+shift+r doesn't work for my linux firefox, it just reloads the page. But then again, my FF has tons of addons etc.

* alt + arrows for jump and speed <- this seems fine to me
* enter to stop <- so not intuitive, is alt+space possible ? It would be more coherent with the line above and easier on the fingers.
* esc to exit <- intuitive, will probably not interfere with much, seems fine


edit : not related but could you add a string in the settings indicating that localstorage is needed for it to work ?

**Comment by jamestomasino** [comment]
I did some investigating and unfortunately the modifier keys (alt/shift,etc) don't work with space in the javascript bindings. That's really frustrating that alt+shift+r isn't working for you to launch Stutter. I was pretty sure that one was safe. The ctrl-shift bindings do conflict with some browser behavior (ctrl-shift-r, ctrl-shift-t, for instance). I thought the alt+shift combo was safe.

If Stutter weren't designed to work on pretty much any page it would be easier to just to pick simple letter bindings, but so many websites already do that it's easy to conflict.

So, here's what I'm looking at:

- Alt+R - Start/Restart Stutter on full page (formerly Alt+Shift+R)
- Alt+P - Pause/Resume (formerly Enter)
- Alt+Left - Skip backwards
- Alt+Right - Skip forwards
- Alt+Up - Increase WPM by 50 (formerly 100)
- Alt+Down - Decrease WPM by 50 (formerly 100)
- Esc - Close Stutter (also works while holding Alt, just in case)

This will unify all the keys under the Alt prefix, but none of them should align with the menu options and should therefore not cause issues (I hope). The only thing that messes with the browser is the alt-left & alt-right. I guess it's not a big issue, though because you could just hit Esc first, then do it and the keys will work.

**Comment by jamestomasino** [comment]
Okay, just implemented this in v1.9.4. We'll see how that goes. I'll leave this issue open a bit longer just in case.

**Comment by thiswillbeyourgithub** [comment]
Okay, thanks !

**Comment by jamestomasino** [comment]
Okay, this seems good to me in both Chrome & FF. Closing.
