### ISSUE TITLE
make stutter shortcut read the selected paragraph if any

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#51]
Hi,

Would it be possible for the stutter shortcut to read the whole page only if no text is selected and if some text is selected then read only this section ?

Thanks !

**Comment by jamestomasino** [comment]
I think this is doable, but not super easy. The trigger to start the add-on is configured in the manifest.json and triggers an action in the background script. Normally I use this to trigger the full page process. That passes the buck through messaging to the content script that gets dynamically loaded. The good news is, it's the content script that would need to exist in order to check for selected copy, so I can interrupt the 'full-page' process and do that check first. If I find something I'll stutter the selection, and if not I can fall back on full-page.

Looks like there's a pretty straight-forward way to check for selected text [on stack overflow for reference.](https://stackoverflow.com/a/5379408)

**Comment by jamestomasino** [comment]
Boom! v1.9.10, just released.
